apiVersion: v1
kind: ConfigMap
metadata:
  namespace: red-planner
  name: app-config
data:
  APPLICATION_PORT: "4200"
  ALLOWED_ORIGIN: "http://red-planner.local"
  SERVER_URL: "http://red-planner.local/api"
  APP_URL: "http://red-planner.local"