apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "mysecretpassword"
  JWT_SECRET: "ksdaOP@cd"
  # DATABASE_URL соберем динамически или положим целиком
  DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres-service:5432/redplanner"
